### ISSUE TITLE
Enhance K8s Metadata link and enriching logs and metrics with namespace labels

### ISSUE THREAD

**Issue by dariuslwh95** [kube-logging/kube-logging.github.io#210]
enhance k8s metada link goes to repo that does not exist, is there a repo I can view to understand and configure the plugin better?
https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/fluent-plugin-enhance-k8s-metadata

my use case is to append namespace labels pod logs collected by the logging operator at /var/log/containers
is there a method this can be accomplished now?
Here are some of the previous issues on this topic that i've viewed, doesnt seem like this feature has been added, would appreciate any help on configuring enhance k8s metadata or otherwise! 
https://github.com/kube-logging/logging-operator/issues/1148
https://github.com/kube-logging/logging-operator/issues/704

**Comment by pepov** [comment]
hey @dariuslwh95 !

The correct link is this: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/tree/main/fluent-plugin-enhance-k8s-metadata and I've created a PR to fix it: https://github.com/kube-logging/logging-operator/pull/1639

As discussed in the linked issues I beleive namespace labels are still not supported in the `enhance-k8s-metadata` plugin and the other plugin `kubernetes-metadata-filter` is still not supported by the logging operator.

**Comment by pepov** [comment]
@dariuslwh95 also as I mentioned in the first issue https://github.com/fluent/fluent-bit/pull/8279 will likely solve this problem very soon.
