### ISSUE TITLE
Simple tutorial does not work

### ISSUE THREAD

**Issue by aslafy-z** [kube-logging/kube-logging.github.io#236]
https://github.com/kube-logging/kube-logging.github.io/blob/master/content/docs/quickstarts/single.md

FluentbitAgents are not processed, No fluentd are deployed.

Setting `logging.enabled: true` fixes it

**Comment by pepov** [comment]
In the example we suggest to create the resources manually, not through `logging.enabled: true`

**Comment by aslafy-z** [comment]
Mmpf, I my previous tests the fluentbitagent resources were not being reconciled. I tried again in a kind clusters, and it worked. I must have missed something. Sorry for that, closing.
